### ISSUE TITLE
Remove the HWID Import in the Main class.

### ISSUE THREAD

**Issue by Intel-i80486-DX4** [master7720/kisman.cc-b0.1.6.1-plus-cracked#3]
It's whats causing the crash. (Along with any instances of "throw new NoStackTraceThrowable()" )

**Comment by master7720** [comment]
too lazy plus i am sick

**Comment by Intel-i80486-DX4** [comment]
Come on, Don't be a lazy-arse, It's like 6 lines.

**Comment by Intel-i80486-DX4** [comment]
**Six fucking lines**

**Comment by M3gaPixel** [comment]
6 lines 😮

**Comment by master7720** [comment]
> **Six fucking lines**

fork it and do it baby girl

**Comment by M3gaPixel** [comment]
i hope you know removing the hwid is still useless as this is only a shitty decomp

**Comment by master7720** [comment]
> i hope you know removing the hwid is still useless as this is only a shitty decomp

cope + you do it better then

**Comment by Intel-i80486-DX4** [comment]
I was talking about recaf-ing it, but I'm entirely IQ'nt, and I was text-shouting at you to do it because I'm a lazy POS.
